//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace COMSTU.com.sidpayment.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SidApiSoap", Namespace="http://tempuri.org/")]
    public partial class SidApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback sid_order_queryOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_getbankmarkupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_getbanksummarybreakdownOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_getbanksummaryreportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_getbillingtotalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_getconsolidatedtransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_getdashboardsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_getmerchantterminalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_getMerchantURLInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_getperiodreportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_getsearchresultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_gettransactioncomparisonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_gettransactiondetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_gettransactionprogressOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_gettransactionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SidApi() {
            this.Url = global::COMSTU.Properties.Settings.Default.COMSTU_com_sidpayment_www_SidApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenticationCompletedEventHandler AuthenticationCompleted;
        
        /// <remarks/>
        public event sid_order_queryCompletedEventHandler sid_order_queryCompleted;
        
        /// <remarks/>
        public event ws_getbankmarkupCompletedEventHandler ws_getbankmarkupCompleted;
        
        /// <remarks/>
        public event ws_getbanksummarybreakdownCompletedEventHandler ws_getbanksummarybreakdownCompleted;
        
        /// <remarks/>
        public event ws_getbanksummaryreportCompletedEventHandler ws_getbanksummaryreportCompleted;
        
        /// <remarks/>
        public event ws_getbillingtotalsCompletedEventHandler ws_getbillingtotalsCompleted;
        
        /// <remarks/>
        public event ws_getconsolidatedtransactionsCompletedEventHandler ws_getconsolidatedtransactionsCompleted;
        
        /// <remarks/>
        public event ws_getdashboardsCompletedEventHandler ws_getdashboardsCompleted;
        
        /// <remarks/>
        public event ws_getmerchantterminalsCompletedEventHandler ws_getmerchantterminalsCompleted;
        
        /// <remarks/>
        public event ws_getMerchantURLInformationCompletedEventHandler ws_getMerchantURLInformationCompleted;
        
        /// <remarks/>
        public event ws_getperiodreportCompletedEventHandler ws_getperiodreportCompleted;
        
        /// <remarks/>
        public event ws_getsearchresultsCompletedEventHandler ws_getsearchresultsCompleted;
        
        /// <remarks/>
        public event ws_gettransactioncomparisonCompletedEventHandler ws_gettransactioncomparisonCompleted;
        
        /// <remarks/>
        public event ws_gettransactiondetailsCompletedEventHandler ws_gettransactiondetailsCompleted;
        
        /// <remarks/>
        public event ws_gettransactionprogressCompletedEventHandler ws_gettransactionprogressCompleted;
        
        /// <remarks/>
        public event ws_gettransactionsCompletedEventHandler ws_gettransactionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Authentication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Authentication(string XML) {
            object[] results = this.Invoke("Authentication", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticationAsync(string XML) {
            this.AuthenticationAsync(XML, null);
        }
        
        /// <remarks/>
        public void AuthenticationAsync(string XML, object userState) {
            if ((this.AuthenticationOperationCompleted == null)) {
                this.AuthenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticationOperationCompleted);
            }
            this.InvokeAsync("Authentication", new object[] {
                        XML}, this.AuthenticationOperationCompleted, userState);
        }
        
        private void OnAuthenticationOperationCompleted(object arg) {
            if ((this.AuthenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticationCompleted(this, new AuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sid_order_query", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sid_order_query(string XML) {
            object[] results = this.Invoke("sid_order_query", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sid_order_queryAsync(string XML) {
            this.sid_order_queryAsync(XML, null);
        }
        
        /// <remarks/>
        public void sid_order_queryAsync(string XML, object userState) {
            if ((this.sid_order_queryOperationCompleted == null)) {
                this.sid_order_queryOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsid_order_queryOperationCompleted);
            }
            this.InvokeAsync("sid_order_query", new object[] {
                        XML}, this.sid_order_queryOperationCompleted, userState);
        }
        
        private void Onsid_order_queryOperationCompleted(object arg) {
            if ((this.sid_order_queryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sid_order_queryCompleted(this, new sid_order_queryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_getbankmarkup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_getbankmarkup(string XML) {
            object[] results = this.Invoke("ws_getbankmarkup", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_getbankmarkupAsync(string XML) {
            this.ws_getbankmarkupAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_getbankmarkupAsync(string XML, object userState) {
            if ((this.ws_getbankmarkupOperationCompleted == null)) {
                this.ws_getbankmarkupOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_getbankmarkupOperationCompleted);
            }
            this.InvokeAsync("ws_getbankmarkup", new object[] {
                        XML}, this.ws_getbankmarkupOperationCompleted, userState);
        }
        
        private void Onws_getbankmarkupOperationCompleted(object arg) {
            if ((this.ws_getbankmarkupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_getbankmarkupCompleted(this, new ws_getbankmarkupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_getbanksummarybreakdown", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_getbanksummarybreakdown(string XML) {
            object[] results = this.Invoke("ws_getbanksummarybreakdown", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_getbanksummarybreakdownAsync(string XML) {
            this.ws_getbanksummarybreakdownAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_getbanksummarybreakdownAsync(string XML, object userState) {
            if ((this.ws_getbanksummarybreakdownOperationCompleted == null)) {
                this.ws_getbanksummarybreakdownOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_getbanksummarybreakdownOperationCompleted);
            }
            this.InvokeAsync("ws_getbanksummarybreakdown", new object[] {
                        XML}, this.ws_getbanksummarybreakdownOperationCompleted, userState);
        }
        
        private void Onws_getbanksummarybreakdownOperationCompleted(object arg) {
            if ((this.ws_getbanksummarybreakdownCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_getbanksummarybreakdownCompleted(this, new ws_getbanksummarybreakdownCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_getbanksummaryreport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_getbanksummaryreport(string XML) {
            object[] results = this.Invoke("ws_getbanksummaryreport", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_getbanksummaryreportAsync(string XML) {
            this.ws_getbanksummaryreportAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_getbanksummaryreportAsync(string XML, object userState) {
            if ((this.ws_getbanksummaryreportOperationCompleted == null)) {
                this.ws_getbanksummaryreportOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_getbanksummaryreportOperationCompleted);
            }
            this.InvokeAsync("ws_getbanksummaryreport", new object[] {
                        XML}, this.ws_getbanksummaryreportOperationCompleted, userState);
        }
        
        private void Onws_getbanksummaryreportOperationCompleted(object arg) {
            if ((this.ws_getbanksummaryreportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_getbanksummaryreportCompleted(this, new ws_getbanksummaryreportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_getbillingtotals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_getbillingtotals(string XML) {
            object[] results = this.Invoke("ws_getbillingtotals", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_getbillingtotalsAsync(string XML) {
            this.ws_getbillingtotalsAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_getbillingtotalsAsync(string XML, object userState) {
            if ((this.ws_getbillingtotalsOperationCompleted == null)) {
                this.ws_getbillingtotalsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_getbillingtotalsOperationCompleted);
            }
            this.InvokeAsync("ws_getbillingtotals", new object[] {
                        XML}, this.ws_getbillingtotalsOperationCompleted, userState);
        }
        
        private void Onws_getbillingtotalsOperationCompleted(object arg) {
            if ((this.ws_getbillingtotalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_getbillingtotalsCompleted(this, new ws_getbillingtotalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_getconsolidatedtransactions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_getconsolidatedtransactions(string XML) {
            object[] results = this.Invoke("ws_getconsolidatedtransactions", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_getconsolidatedtransactionsAsync(string XML) {
            this.ws_getconsolidatedtransactionsAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_getconsolidatedtransactionsAsync(string XML, object userState) {
            if ((this.ws_getconsolidatedtransactionsOperationCompleted == null)) {
                this.ws_getconsolidatedtransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_getconsolidatedtransactionsOperationCompleted);
            }
            this.InvokeAsync("ws_getconsolidatedtransactions", new object[] {
                        XML}, this.ws_getconsolidatedtransactionsOperationCompleted, userState);
        }
        
        private void Onws_getconsolidatedtransactionsOperationCompleted(object arg) {
            if ((this.ws_getconsolidatedtransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_getconsolidatedtransactionsCompleted(this, new ws_getconsolidatedtransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_getdashboards", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_getdashboards(string XML) {
            object[] results = this.Invoke("ws_getdashboards", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_getdashboardsAsync(string XML) {
            this.ws_getdashboardsAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_getdashboardsAsync(string XML, object userState) {
            if ((this.ws_getdashboardsOperationCompleted == null)) {
                this.ws_getdashboardsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_getdashboardsOperationCompleted);
            }
            this.InvokeAsync("ws_getdashboards", new object[] {
                        XML}, this.ws_getdashboardsOperationCompleted, userState);
        }
        
        private void Onws_getdashboardsOperationCompleted(object arg) {
            if ((this.ws_getdashboardsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_getdashboardsCompleted(this, new ws_getdashboardsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_getmerchantterminals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_getmerchantterminals(string XML) {
            object[] results = this.Invoke("ws_getmerchantterminals", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_getmerchantterminalsAsync(string XML) {
            this.ws_getmerchantterminalsAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_getmerchantterminalsAsync(string XML, object userState) {
            if ((this.ws_getmerchantterminalsOperationCompleted == null)) {
                this.ws_getmerchantterminalsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_getmerchantterminalsOperationCompleted);
            }
            this.InvokeAsync("ws_getmerchantterminals", new object[] {
                        XML}, this.ws_getmerchantterminalsOperationCompleted, userState);
        }
        
        private void Onws_getmerchantterminalsOperationCompleted(object arg) {
            if ((this.ws_getmerchantterminalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_getmerchantterminalsCompleted(this, new ws_getmerchantterminalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_getMerchantURLInformation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_getMerchantURLInformation(string XML) {
            object[] results = this.Invoke("ws_getMerchantURLInformation", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_getMerchantURLInformationAsync(string XML) {
            this.ws_getMerchantURLInformationAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_getMerchantURLInformationAsync(string XML, object userState) {
            if ((this.ws_getMerchantURLInformationOperationCompleted == null)) {
                this.ws_getMerchantURLInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_getMerchantURLInformationOperationCompleted);
            }
            this.InvokeAsync("ws_getMerchantURLInformation", new object[] {
                        XML}, this.ws_getMerchantURLInformationOperationCompleted, userState);
        }
        
        private void Onws_getMerchantURLInformationOperationCompleted(object arg) {
            if ((this.ws_getMerchantURLInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_getMerchantURLInformationCompleted(this, new ws_getMerchantURLInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_getperiodreport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_getperiodreport(string XML) {
            object[] results = this.Invoke("ws_getperiodreport", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_getperiodreportAsync(string XML) {
            this.ws_getperiodreportAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_getperiodreportAsync(string XML, object userState) {
            if ((this.ws_getperiodreportOperationCompleted == null)) {
                this.ws_getperiodreportOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_getperiodreportOperationCompleted);
            }
            this.InvokeAsync("ws_getperiodreport", new object[] {
                        XML}, this.ws_getperiodreportOperationCompleted, userState);
        }
        
        private void Onws_getperiodreportOperationCompleted(object arg) {
            if ((this.ws_getperiodreportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_getperiodreportCompleted(this, new ws_getperiodreportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_getsearchresults", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_getsearchresults(string XML) {
            object[] results = this.Invoke("ws_getsearchresults", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_getsearchresultsAsync(string XML) {
            this.ws_getsearchresultsAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_getsearchresultsAsync(string XML, object userState) {
            if ((this.ws_getsearchresultsOperationCompleted == null)) {
                this.ws_getsearchresultsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_getsearchresultsOperationCompleted);
            }
            this.InvokeAsync("ws_getsearchresults", new object[] {
                        XML}, this.ws_getsearchresultsOperationCompleted, userState);
        }
        
        private void Onws_getsearchresultsOperationCompleted(object arg) {
            if ((this.ws_getsearchresultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_getsearchresultsCompleted(this, new ws_getsearchresultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_gettransactioncomparison", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_gettransactioncomparison(string XML) {
            object[] results = this.Invoke("ws_gettransactioncomparison", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_gettransactioncomparisonAsync(string XML) {
            this.ws_gettransactioncomparisonAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_gettransactioncomparisonAsync(string XML, object userState) {
            if ((this.ws_gettransactioncomparisonOperationCompleted == null)) {
                this.ws_gettransactioncomparisonOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_gettransactioncomparisonOperationCompleted);
            }
            this.InvokeAsync("ws_gettransactioncomparison", new object[] {
                        XML}, this.ws_gettransactioncomparisonOperationCompleted, userState);
        }
        
        private void Onws_gettransactioncomparisonOperationCompleted(object arg) {
            if ((this.ws_gettransactioncomparisonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_gettransactioncomparisonCompleted(this, new ws_gettransactioncomparisonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_gettransactiondetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_gettransactiondetails(string XML) {
            object[] results = this.Invoke("ws_gettransactiondetails", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_gettransactiondetailsAsync(string XML) {
            this.ws_gettransactiondetailsAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_gettransactiondetailsAsync(string XML, object userState) {
            if ((this.ws_gettransactiondetailsOperationCompleted == null)) {
                this.ws_gettransactiondetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_gettransactiondetailsOperationCompleted);
            }
            this.InvokeAsync("ws_gettransactiondetails", new object[] {
                        XML}, this.ws_gettransactiondetailsOperationCompleted, userState);
        }
        
        private void Onws_gettransactiondetailsOperationCompleted(object arg) {
            if ((this.ws_gettransactiondetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_gettransactiondetailsCompleted(this, new ws_gettransactiondetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_gettransactionprogress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_gettransactionprogress(string XML) {
            object[] results = this.Invoke("ws_gettransactionprogress", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_gettransactionprogressAsync(string XML) {
            this.ws_gettransactionprogressAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_gettransactionprogressAsync(string XML, object userState) {
            if ((this.ws_gettransactionprogressOperationCompleted == null)) {
                this.ws_gettransactionprogressOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_gettransactionprogressOperationCompleted);
            }
            this.InvokeAsync("ws_gettransactionprogress", new object[] {
                        XML}, this.ws_gettransactionprogressOperationCompleted, userState);
        }
        
        private void Onws_gettransactionprogressOperationCompleted(object arg) {
            if ((this.ws_gettransactionprogressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_gettransactionprogressCompleted(this, new ws_gettransactionprogressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ws_gettransactions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ws_gettransactions(string XML) {
            object[] results = this.Invoke("ws_gettransactions", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_gettransactionsAsync(string XML) {
            this.ws_gettransactionsAsync(XML, null);
        }
        
        /// <remarks/>
        public void ws_gettransactionsAsync(string XML, object userState) {
            if ((this.ws_gettransactionsOperationCompleted == null)) {
                this.ws_gettransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_gettransactionsOperationCompleted);
            }
            this.InvokeAsync("ws_gettransactions", new object[] {
                        XML}, this.ws_gettransactionsOperationCompleted, userState);
        }
        
        private void Onws_gettransactionsOperationCompleted(object arg) {
            if ((this.ws_gettransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_gettransactionsCompleted(this, new ws_gettransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AuthenticationCompletedEventHandler(object sender, AuthenticationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void sid_order_queryCompletedEventHandler(object sender, sid_order_queryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sid_order_queryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sid_order_queryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_getbankmarkupCompletedEventHandler(object sender, ws_getbankmarkupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_getbankmarkupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_getbankmarkupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_getbanksummarybreakdownCompletedEventHandler(object sender, ws_getbanksummarybreakdownCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_getbanksummarybreakdownCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_getbanksummarybreakdownCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_getbanksummaryreportCompletedEventHandler(object sender, ws_getbanksummaryreportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_getbanksummaryreportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_getbanksummaryreportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_getbillingtotalsCompletedEventHandler(object sender, ws_getbillingtotalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_getbillingtotalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_getbillingtotalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_getconsolidatedtransactionsCompletedEventHandler(object sender, ws_getconsolidatedtransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_getconsolidatedtransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_getconsolidatedtransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_getdashboardsCompletedEventHandler(object sender, ws_getdashboardsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_getdashboardsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_getdashboardsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_getmerchantterminalsCompletedEventHandler(object sender, ws_getmerchantterminalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_getmerchantterminalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_getmerchantterminalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_getMerchantURLInformationCompletedEventHandler(object sender, ws_getMerchantURLInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_getMerchantURLInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_getMerchantURLInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_getperiodreportCompletedEventHandler(object sender, ws_getperiodreportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_getperiodreportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_getperiodreportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_getsearchresultsCompletedEventHandler(object sender, ws_getsearchresultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_getsearchresultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_getsearchresultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_gettransactioncomparisonCompletedEventHandler(object sender, ws_gettransactioncomparisonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_gettransactioncomparisonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_gettransactioncomparisonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_gettransactiondetailsCompletedEventHandler(object sender, ws_gettransactiondetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_gettransactiondetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_gettransactiondetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_gettransactionprogressCompletedEventHandler(object sender, ws_gettransactionprogressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_gettransactionprogressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_gettransactionprogressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ws_gettransactionsCompletedEventHandler(object sender, ws_gettransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_gettransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_gettransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591